name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2
        run: |
          scp -i erp.pem -r ./* ubuntu@ec2-18-118-7-108.us-east-2.compute.amazonaws.com:/home/ubuntu/python-todo-cicd
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }} 'cd /home/ubuntu/python-todo-cicd && sudo python3 manage.py runserver 0.0.0.0:8000'
