name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Django migrations
        run: python manage.py migrate

      - name: Run Django tests
        run: python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2
        run: |
          scp -i erp.pem -r ./* ubuntu@ec2-18-118-7-108.us-east-2.compute.amazonaws.com:/home/ubuntu/python-todo-cicd
          ssh -i erp.pem ubuntu@ec2-18-118-7-108.us-east-2.compute.amazonaws.com 'cd /home/ubuntu/python-todo-cicd && sudo python manage.py migrate && sudo python manage.py collectstatic --noinput && sudo systemctl restart your-app.service'
